### ISSUE TITLE
Sql: adesione di più scuole ad un progetto

### ISSUE THREAD

**Issue by profcolle** [VanessaBertoldi/ProgettoOltre#2]
Modifica del database in modo da permettere a più scuole di aderire ad un progetto (di cui una come owner)
Le attività verranno associate direttamente ad una sola scuola e ad un solo progetto.
Gli eventi rimangono associati ad una sola attività
Le organization si associano al progetto o alla attività?

**Comment by Cellana** [comment]
Modifica del database in modo da permettere a più scuole di aderire ad un progetto: EFFETTUATA.
Le organizzazioni (GB_Organization) si associano all'attività.
